### ISSUE TITLE
Web interface - Dispaly isn't shown

### ISSUE THREAD

**Issue by SRadiant** [RigacciOrg/AirPi#2]
Hi, RigacciOrg. I installed the AirPi following Software setup step in website. 
It can read the data from BME280 (I don't get PMS5003 yet). But when I open the web interface, the "Display" site isn't shown any data, totally blank. And open the .csv form "Data Download" show "ERROR: airpi-data-export: Error reading the database: no such table: data".
However the "Graphs" site work well.
How can I fix it? Help me, please. Thank you.

**Comment by SRadiant** [comment]
Thank you for your response. I'm trying find out the problem.
When I run "sudo /usr/local/lib/airpi/airpi-data-store", 
ERROR:root:airpi-data-store: Reading PMS5003 status file: [Errno 2] No such file or directory: '/var/run/pms5003.status'
ERROR:root:airpi-data-store: Parsing PMS5003 status file: name 'data' is not defined
(I don't get PMS5003 yet)
Is it fine?
My RPi autologin user "pi" when start. I have to add sudo in front of executing any script. Is it possible permission problem?

**Comment by RigacciOrg** [comment]
The error reading PMS5003 status data is OK, since you don't have that sensor; this error should be non fatal. Check if the SQLite database is created: **/var/lib/airpi/airpi-data.db**. The file should be owned by **root:root**, permissions **-rw-r--r--**
Try the commands on the command line as root: execute **sudo su -** once and you don't need sudo anymore in that ssh session.

**Comment by SRadiant** [comment]
/var/lib/airpi/airpi-data.db was created, and  permissions -rw-r--r--, too.
I had executing some script separately...
![image](https://user-images.githubusercontent.com/46018730/50884227-3a8a5300-1425-11e9-8beb-a731c732a0ac.png)
![image](https://user-images.githubusercontent.com/46018730/50884242-45dd7e80-1425-11e9-8618-a27fee75cbb5.png)
![image](https://user-images.githubusercontent.com/46018730/50884245-483fd880-1425-11e9-902c-13cb110c1d91.png)
![image](https://user-images.githubusercontent.com/46018730/50884248-4bd35f80-1425-11e9-9688-b518d09ee0e0.png)

**Comment by happynitron** [comment]
did you guys figure out it? i'm too facing like this problem.
what can you suggest for the below error?
`root@john:/var/www/html# /usr/local/lib/airpi/airpi-data-http-post
INFO:root:airpi-data-http-post: Communicating with post_data.php
Traceback (most recent call last):
  File "/usr/local/lib/airpi/airpi-data-http-post", line 54, in <module>
    r = requests.post(HTTP_REQUEST_URL, verify=False, data={'login': HTTP_LOGIN, 'password': HTTP_PASSWORD})
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 366, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'localhost/airpi/post_data.php': No schema supplied. Perhaps you meant http://localhost/airpi/post_data.php?
`

`root@john:/var/www/html# /usr/local/lib/airpi/airpi-data-mqtt-pub
ERROR:root:airpi-data-mqtt-pub: Cannot get timestamp: [Errno 2] No such file or directory: '/var/lib/airpi/mqtt-timestamp'
INFO:root:airpi-data-mqtt-pub: Latest upload: 1970-01-01T00:00:00Z
ERROR:root:airpi-data-mqtt-pub: Error reading the database: no such table: data
`

**Comment by sbdevarakonda** [comment]
How do you get to the web interface? It is not mentioned anywhere.  Sorry, I am a novice in this field. Can someone explain the steps. Thanks.
